apiVersion: v1
kind: Service
metadata:
  name: vue-app
  labels:
    app: vue-app
spec:
  selector:
    app: vue-app
  type: LoadBalancer  
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP 