apiVersion: v1
kind: Service
metadata:
  name: container-app
  labels:
    app: container-app
spec:
  selector:
    app: container-app
  type: LoadBalancer
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP 